/*
 * * Copyright 1987-2022 ANSYS, Inc. All Rights Reserved.
 */

/* these provide serial stubs for parallel functions;
 * parallel calls are resolved from multiport */

#ifndef _PAR_STUBS_H
#define _PAR_STUBS_H

FLUENT_EXPORT int MPT_Is_System_Homogeneous(int with_host);

FLUENT_EXPORT void MPT_sharedCounter_init(int istart);
FLUENT_EXPORT int  MPT_sharedCounter_server(void);
FLUENT_EXPORT int  MPT_sharedCounter_get(void);
FLUENT_EXPORT void MPT_sharedCounter_exit(void);

#define host_to_node_boolean_1(a)
#define host_to_node_boolean_2(a,b)
#define host_to_node_boolean_3(a,b,c)
#define host_to_node_boolean_4(a,b,c,d)
#define host_to_node_boolean_5(a,b,c,d,e)
#define host_to_node_boolean_6(a,b,c,d,e,f)
#define host_to_node_boolean_7(a,b,c,d,e,f,g)
#define host_to_node_double_1(a)
#define host_to_node_double_2(a,b)
#define host_to_node_double_3(a,b,c)
#define host_to_node_double_4(a,b,c,d)
#define host_to_node_double_5(a,b,c,d,e)
#define host_to_node_double_6(a,b,c,d,e,f)
#define host_to_node_double_7(a,b,c,d,e,f,g)
#define host_to_node_double_8(a,b,c,d,e,f,g,h)
#define host_to_node_double_9(a,b,c,d,e,f,g,h,i)
#define host_to_node_int_1(a)
#define host_to_node_int_2(a,b)
#define host_to_node_int_3(a,b,c)
#define host_to_node_int_4(a,b,c,d)
#define host_to_node_int_5(a,b,c,d,e)
#define host_to_node_int_6(a,b,c,d,e,f)
#define host_to_node_int_7(a,b,c,d,e,f,g)
#define host_to_node_int64_1(a)
#define host_to_node_int64_2(a,b)
#define host_to_node_long_1(a)
#define host_to_node_long_2(a,b)
#define host_to_node_long_3(a,b,c)
#define host_to_node_long_4(a,b,c,d)
#define host_to_node_long_5(a,b,c,d,e)
#define host_to_node_long_6(a,b,c,d,e,f)
#define host_to_node_long_7(a,b,c,d,e,f,g)
#define host_to_node_long_long_1(a)
#define host_to_node_long_long_2(a,b)
#define host_to_node_long_long_3(a,b,c)
#define host_to_node_long_long_4(a,b,c,d)
#define host_to_node_long_long_5(a,b,c,d,e)
#define host_to_node_long_long_6(a,b,c,d,e,f)
#define host_to_node_long_long_7(a,b,c,d,e,f,g)
#define host_to_node_real_1(a)
#define host_to_node_real_2(a,b)
#define host_to_node_real_3(a,b,c)
#define host_to_node_real_4(a,b,c,d)
#define host_to_node_real_5(a,b,c,d,e)
#define host_to_node_real_6(a,b,c,d,e,f)
#define host_to_node_real_7(a,b,c,d,e,f,g)
#define host_to_node_real_8(a,b,c,d,e,f,g,h)
#define host_to_node_real_9(a,b,c,d,e,f,g,h,i)
#define host_to_node_float_1(a)
#define host_to_node_float_2(a,b)
#define host_to_node_float_3(a,b,c)
#define host_to_node_float_4(a,b,c,d)
#define host_to_node_float_5(a,b,c,d,e)
#define host_to_node_float_6(a,b,c,d,e,f)
#define host_to_node_float_7(a,b,c,d,e,f,g)
#define host_to_node_float_8(a,b,c,d,e,f,g,h)
#define host_to_node_float_9(a,b,c,d,e,f,g,h,i)
#define host_to_node_real(a,b)
#define host_to_node_float(a,b)
#define host_to_node_double(a,b)
#define host_to_node_int(a,b)
#define host_to_node_long(a,b)
#define host_to_node_long_long(a,b)
#define host_to_node_boolean(a,b)
#define host_to_node_string(a,b)
#define host_to_node_enum_1(a)

#define host_to_node_sync_file(f)

#define node_to_host_boolean_1(a)
#define node_to_host_double_1(a)
#define node_to_host_double_2(a,b)
#define node_to_host_double_3(a,b,c)
#define node_to_host_double_4(a,b,c,d)
#define node_to_host_double_5(a,b,c,d,e)
#define node_to_host_double_6(a,b,c,d,e,f)
#define node_to_host_double_7(a,b,c,d,e,f,g)
#define node_to_host_int_1(a)
#define node_to_host_int_2(a,b)
#define node_to_host_int_3(a,b,c)
#define node_to_host_int_4(a,b,c,d)
#define node_to_host_int_5(a,b,c,d,e)
#define node_to_host_int_6(a,b,c,d,e,f)
#define node_to_host_int_7(a,b,c,d,e,f,g)
#define host_to_node_int64_1(a)
#define host_to_node_int64_2(a,b)
#define node_to_host_long_1(a)
#define node_to_host_long_2(a,b)
#define node_to_host_long_3(a,b,c)
#define node_to_host_long_4(a,b,c,d)
#define node_to_host_long_5(a,b,c,d,e)
#define node_to_host_long_6(a,b,c,d,e,f)
#define node_to_host_long_7(a,b,c,d,e,f,g)
#define node_to_host_long_long_1(a)
#define node_to_host_long_long_2(a,b)
#define node_to_host_long_long_3(a,b,c)
#define node_to_host_long_long_4(a,b,c,d)
#define node_to_host_long_long_5(a,b,c,d,e)
#define node_to_host_long_long_6(a,b,c,d,e,f)
#define node_to_host_long_long_7(a,b,c,d,e,f,g)
#define node_to_host_real_1(a)
#define node_to_host_real_2(a,b)
#define node_to_host_real_3(a,b,c)
#define node_to_host_real_4(a,b,c,d)
#define node_to_host_real_5(a,b,c,d,e)
#define node_to_host_real_6(a,b,c,d,e,f)
#define node_to_host_real_7(a,b,c,d,e,f,g)
#define node_to_host_float_1(a)
#define node_to_host_float_2(a,b)
#define node_to_host_float_3(a,b,c)
#define node_to_host_float_4(a,b,c,d)
#define node_to_host_float_5(a,b,c,d,e)
#define node_to_host_float_6(a,b,c,d,e,f)
#define node_to_host_float_7(a,b,c,d,e,f,g)
#define node_to_host_real(a,b)
#define node_to_host_float(a,b)
#define node_to_host_double(a,b)
#define node_to_host_int(a,b)
#define node_to_host_long(a,b)
#define node_to_host_long_long(a,b)
#define node_to_host_boolean(a,b)
#define node_to_host_string(a,b)

#define PTRACE_BEGIN(func)
#define PTRACE_BEGIN_3(func, file, line)
#define PTRACE_END()

#define DEBUG_PAR()
#define DEBUG_PART()
#define DEBUG_CELL()
#define DEBUG_FACE()
#define OPEN_DEBUG_FILE()

#define BEGIN_SERIALIZE_CODE()
#define END_SERIALIZE_CODE()
#define BEGIN_SERIALIZE_NODES()
#define END_SERIALIZE_NODES()

#endif /* _PAR_STUBS_H */
